name: Haskell CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: ["8.8.3", "8.10.7"]
        cabal: ["3.0", "3.6.2"]
    steps:
      - uses: actions/checkout@v2.4
      - uses: actions/setup-haskell@v1.1.4
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
      - uses: actions/cache@v2.1.7
        name: Cache ~/.cabal/store
        with:
          path: ~/.cabal/store
          key: ${{ runner.os }}-${{ matrix.ghc }}-cabal-store
      - name: Install dependencies
        run: |
          cabal new-update
          cabal new-configure --write-ghc-environment-files=always -j2
          cabal new-build --only-dependencies
      - name: Build & Run Tests
        run: |
          cabal v2-build
          cabal v2-test
