name: Haskell CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: ["8.8.1"]
        cabal: ["3.0"]
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}
    # We cache the elements of the Cabal store separately,
    # as the entirety of ~/.cabal can grow very large
    # for projects with many dependencies.
    - uses: actions/cache@v1
      name: Cache ~/.cabal/packages
      with:
        path: ~/.cabal/packages
        key: ${{ runner.os }}-${{ matrix.ghc }}-cabal-packages
    - uses: actions/cache@v1
      name: Cache ~/.cabal/store
      with:
        path: ~/.cabal/store
        key: ${{ runner.os }}-${{ matrix.ghc }}-cabal-store
    - name: Install dependencies
      run: |
        cabal new-update
        cabal new-configure --write-ghc-environment-files=always -j2
        cabal new-build --only-dependencies
    - name: Build & Run Tests
      run: |
        cabal v2-build
        cabal v2-test
